spring.application.name=Spring-Boot-Tutorial
spring.datasource.url = jdbc:postgresql://localhost:5432/springcohert
spring.datasource.username = postgres
spring.datasource.password = 140301Cer061@

spring.jpa.hibernate.ddl-auto= update
spring.jpa.hibernate.show-sql= true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

